---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    rulesets: "ruleset.xml"
ratings:
  paths:
  - "**.inc"
  - "**.php"
exclude_paths:
  - Tests/**/*
  - XmlElementLookup.php
  - vendor/**/*
